CREATE USER user1 WITH PASSWORD 'pass123';
CREATE DATABASE usertags;
CREATE DATABASE usertags_test;
GRANT ALL PRIVILEGES ON DATABASE usertags TO user1;
GRANT ALL PRIVILEGES ON DATABASE usertags_test TO user1;
